const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.AJAX,
		C3.Plugins.BinaryData,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.Touch,
		C3.Behaviors.Flash,
		C3.Plugins.Mouse,
		C3.Plugins.video,
		C3.Plugins.sliderbar,
		C3.Behaviors.Tween,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.MoveToTop,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Browser.Acts.InvokeDownload,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.sliderbar.Cnds.OnChanging,
		C3.Plugins.video.Acts.SetPlaybackTime,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.video.Cnds.IsPlaying,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.video.Exps.PlaybackTime,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.right,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties
	];
};
self.C3_JsPropNameTable = [
	{arka_giris: 0},
	{btn_basla: 0},
	{btn_kaynakca: 0},
	{btn_bilgi: 0},
	{arka_bilgi: 0},
	{arka_kaynakca: 0},
	{btn_ev: 0},
	{arka_yonerge1: 0},
	{cvplandimi: 0},
	{btn_bozulmak: 0},
	{btn_plastik: 0},
	{btn_fiberglas: 0},
	{btn_kimyasal: 0},
	{btn_geridonusum: 0},
	{btn_sentetik: 0},
	{btn_ambalaj: 0},
	{btn_sembol: 0},
	{btn_bakteri: 0},
	{btn_tekstil: 0},
	{yonerge_1: 0},
	{yonerge1_cvplar: 0},
	{AJAX: 0},
	{BinaryData: 0},
	{Browser: 0},
	{defter: 0},
	{PlatformInfo: 0},
	{Text: 0},
	{TextInput: 0},
	{Touch: 0},
	{btn_kaydet: 0},
	{Flash: 0},
	{btn_ileri: 0},
	{yonerge1_bos: 0},
	{btn_tamamlandi: 0},
	{yonerge1_cvplar2: 0},
	{btn_ses: 0},
	{btn_geri: 0},
	{btn_kaydet2: 0},
	{Mouse: 0},
	{Video: 0},
	{SliderBar: 0},
	{btn_play: 0},
	{gif: 0},
	{arka_yonerge2: 0},
	{yonerge2_ilk: 0},
	{deger: 0},
	{x_konum: 0},
	{y_konum: 0},
	{yonerge2_sorular: 0},
	{btn_yazili: 0},
	{btn_sozlu: 0},
	{yonerge2_yazili: 0},
	{yon2_yazialani: 0},
	{TextInput2: 0},
	{Text2: 0},
	{yonerge2_sorular1: 0},
	{yonerge2_sorular2: 0},
	{yonerge2_sorular3: 0},
	{yonerge2_sorular4: 0},
	{yonerge2_sorular5: 0},
	{yonerge2_sorular6: 0},
	{yonerge2_sorular_yazili: 0},
	{yonerge2_sozlu: 0},
	{timetext: 0},
	{saat: 0},
	{saat_sayilar: 0},
	{arka_bitis: 0},
	{tebrikler: 0},
	{btn_etkinligitamamla: 0},
	{btnlar: 0},
	{sozyaz: 0},
	{yon2sorular: 0},
	{yon1secenekler: 0},
	{Tween: 0},
	{saatvesayisi: 0},
	{screenX: 0},
	{screenY: 0},
	{secim: 0},
	{tiklamasayisi: 0},
	{tamamlandi: 0},
	{yonerge1_secimsayisi: 0},
	{yonerge2_soru0: 0},
	{yonerge2_soru1: 0},
	{yonerge2_soru2: 0},
	{yonerge2_soru3: 0},
	{yonerge2_soru4: 0},
	{yonerge2_soru5: 0},
	{yonerge2_soru6: 0},
	{yonerge2_secimsayisi: 0},
	{secim2: 0},
	{timeCount: 0},
	{isTimeStart: 0}
];

self.InstanceType = {
	arka_giris: class extends self.ISpriteInstance {},
	btn_basla: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_bilgi: class extends self.ISpriteInstance {},
	arka_bilgi: class extends self.ISpriteInstance {},
	arka_kaynakca: class extends self.ISpriteInstance {},
	btn_ev: class extends self.ISpriteInstance {},
	arka_yonerge1: class extends self.ISpriteInstance {},
	btn_bozulmak: class extends self.ISpriteInstance {},
	btn_plastik: class extends self.ISpriteInstance {},
	btn_fiberglas: class extends self.ISpriteInstance {},
	btn_kimyasal: class extends self.ISpriteInstance {},
	btn_geridonusum: class extends self.ISpriteInstance {},
	btn_sentetik: class extends self.ISpriteInstance {},
	btn_ambalaj: class extends self.ISpriteInstance {},
	btn_sembol: class extends self.ISpriteInstance {},
	btn_bakteri: class extends self.ISpriteInstance {},
	btn_tekstil: class extends self.ISpriteInstance {},
	yonerge_1: class extends self.ISpriteInstance {},
	yonerge1_cvplar: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Browser: class extends self.IInstance {},
	defter: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	TextInput: class extends self.ITextInputInstance {},
	Touch: class extends self.IInstance {},
	btn_kaydet: class extends self.ISpriteInstance {},
	btn_ileri: class extends self.ISpriteInstance {},
	yonerge1_bos: class extends self.ISpriteInstance {},
	btn_tamamlandi: class extends self.ISpriteInstance {},
	yonerge1_cvplar2: class extends self.ISpriteInstance {},
	btn_ses: class extends self.ISpriteInstance {},
	btn_geri: class extends self.ISpriteInstance {},
	btn_kaydet2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Video: class extends self.IWorldInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	btn_play: class extends self.ISpriteInstance {},
	gif: class extends self.ISpriteInstance {},
	arka_yonerge2: class extends self.ISpriteInstance {},
	yonerge2_ilk: class extends self.ISpriteInstance {},
	yonerge2_sorular: class extends self.ISpriteInstance {},
	btn_yazili: class extends self.ISpriteInstance {},
	btn_sozlu: class extends self.ISpriteInstance {},
	yonerge2_yazili: class extends self.ISpriteInstance {},
	yon2_yazialani: class extends self.ISpriteInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	Text2: class extends self.ITextInstance {},
	yonerge2_sorular1: class extends self.ISpriteInstance {},
	yonerge2_sorular2: class extends self.ISpriteInstance {},
	yonerge2_sorular3: class extends self.ISpriteInstance {},
	yonerge2_sorular4: class extends self.ISpriteInstance {},
	yonerge2_sorular5: class extends self.ISpriteInstance {},
	yonerge2_sorular6: class extends self.ISpriteInstance {},
	yonerge2_sorular_yazili: class extends self.ISpriteInstance {},
	yonerge2_sozlu: class extends self.ISpriteInstance {},
	timetext: class extends self.ITextInstance {},
	saat: class extends self.ISpriteInstance {},
	saat_sayilar: class extends self.ISpriteInstance {},
	arka_bitis: class extends self.ISpriteInstance {},
	tebrikler: class extends self.ISpriteInstance {},
	btn_etkinligitamamla: class extends self.ISpriteInstance {},
	btnlar: class extends self.ISpriteInstance {},
	sozyaz: class extends self.ISpriteInstance {},
	yon2sorular: class extends self.ISpriteInstance {},
	yon1secenekler: class extends self.ISpriteInstance {},
	saatvesayisi: class extends self.ISpriteInstance {}
}